### ISSUE TITLE
[Bug]: Discord spams messages when rsyslog is present and overfills the log

### ISSUE THREAD

**Issue by mgajda** [snapcrafters/discord#144] opened 2023-01-17 18:09 UTC
### What happened?

Discord spams multiple messages per second:
```
Jan 15 00:00:10 xyr snapd-desktop-integration.snapd-desktop-integration[500947]: Failed to do gtk init
Jan 15 00:00:13 xyr systemd[3638]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled res    tart job, restart counter is at 5943.
Jan 15 00:00:13 xyr systemd[3638]: Stopped Service for snap application snapd-desktop-integration.snapd-desktop-in    tegration.
Jan 15 00:00:13 xyr systemd[3638]: Started Service for snap application snapd-desktop-integration.snapd-desktop-in    tegration.
Jan 15 00:00:13 xyr snapd-desktop-i[501016]: Not loading module "atk-bridge": The functionality is provided by GTK     natively. Please try to not load it.
```

And:
```
Jan 17 18:28:07 xyr discord_discord.desktop[6468]: [6468:0117/182807.238291:ERROR:process_singleton_posix.cc(667)]     accept() failed: Operation not permitted (1)
```

This happens until disk runs out of disk space (I reached over 450GB since Discord was started today. /var/log/syslog after `egrep -v -i 'discord|desktop-integration' is only 12MB.)

### What should have happened?

The Discord should recognize that system integration is unavailable, and stop restarting it.
It should also recognize that singleton process communication will not work, and use exponential backoff.

If nothing else, at least the messages should be blocked from entering the log beyond certain bounds.

### Output of `snap info discord`

```shell
name:      discord
summary:   All-in-one voice and text chat for gamers
publisher: Snapcrafters
store-url: https://snapcraft.io/discord
contact:   https://github.com/snapcrafters/discord/issues
license:   unset
description: |
  All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and
  phone.
  
  Snaps are confined, as such Discord may be unable to perform some of the tasks it typically does
  when unconfined. This may result in the system log getting spammed with apparmor errors. Granting
  access to the system-observe interface when in the snap will enable the features, and thus reduce
  the logging.
  
      snap connect discord:system-observe
  
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - discord
snap-id:      qHVefGEBezeuCeSfTND40uoUD6GRw8BO
tracking:     latest/stable
refresh-date: 4 days ago, at 23:34 UTC
channels:
  latest/stable:    0.0.23 2023-01-13 (147) 90MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      0.0.24 2023-01-16 (149) 85MB -
installed:          0.0.23            (147) 90MB -

```
```


### Output of `snap connections discord`

```shell
Interface               Plug                            Slot                            Notes
audio-playback          discord:audio-playback          :audio-playback                 -
audio-record            discord:audio-record            :audio-record                   -
camera                  discord:camera                  -                               -
content[gnome-42-2204]  discord:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   discord:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    discord:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   discord:sound-themes            gtk-common-themes:sound-themes  -
desktop                 discord:desktop                 :desktop                        -
desktop-legacy          discord:desktop-legacy          -                               -
gsettings               discord:gsettings               :gsettings                      -
home                    discord:home                    :home                           -
mount-observe           discord:mount-observe           -                               -
network                 discord:network                 :network                        -
network-observe         discord:network-observe         -                               -
opengl                  discord:opengl                  :opengl                         -
process-control         discord:process-control         -                               -
removable-media         discord:removable-media         -                               -
screen-inhibit-control  discord:screen-inhibit-control  :screen-inhibit-control         -
shared-memory           discord:shmem                   :shared-memory                  -
system-observe          discord:system-observe          :system-observe                 manual
unity7                  discord:unity7                  -                               -
wayland                 discord:wayland                 :wayland                        -
x11                     discord:x11                     :x11                            -

```

### Output of `snap version`

```shell
2.58
snapd   2.58
series  16
ubuntu  22.04
kernel  5.15.0-57-lowlatency
```

### Relevant log output

```shell
Jan 15 00:00:10 xyr snapd-desktop-integration.snapd-desktop-integration[500947]: Failed to do gtk init
Jan 15 00:00:13 xyr systemd[3638]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled res    tart job, restart counter is at 5943.
Jan 15 00:00:13 xyr systemd[3638]: Stopped Service for snap application snapd-desktop-integration.snapd-desktop-in    tegration.
Jan 15 00:00:13 xyr systemd[3638]: Started Service for snap application snapd-desktop-integration.snapd-desktop-in    tegration.
Jan 15 00:00:13 xyr snapd-desktop-i[501016]: Not loading module "atk-bridge": The functionality is provided by GTK     natively. Please try to not load it.
```

```
Jan 17 18:28:07 xyr discord_discord.desktop[6468]: [6468:0117/182807.238291:ERROR:process_singleton_posix.cc(667)]     accept() failed: Operation not permitted (1)
```
```
Jan 17 18:26:57 xyr kernel: [  177.256583] kauditd_printk_skb: 589137 callbacks suppressed
Jan 17 18:27:02 xyr kernel: [  182.257426] kauditd_printk_skb: 607518 callbacks suppressed
Jan 17 18:27:07 xyr kernel: [  187.258292] kauditd_printk_skb: 551754 callbacks suppressed
Jan 17 18:27:12 xyr kernel: [  192.259165] kauditd_printk_skb: 537314 callbacks suppressed
Jan 17 18:27:17 xyr kernel: [  197.260044] kauditd_printk_skb: 570309 callbacks suppressed
Jan 17 18:27:22 xyr kernel: [  202.260941] kauditd_printk_skb: 541521 callbacks suppressed
Jan 17 18:27:27 xyr kernel: [  207.261837] kauditd_printk_skb: 519826 callbacks suppressed
Jan 17 18:27:32 xyr kernel: [  212.262745] kauditd_printk_skb: 591629 callbacks suppressed
Jan 17 18:27:37 xyr kernel: [  217.263667] kauditd_printk_skb: 580380 callbacks suppressed
Jan 17 18:27:42 xyr kernel: [  222.264578] kauditd_printk_skb: 572899 callbacks suppressed
Jan 17 18:27:47 xyr kernel: [  227.265499] kauditd_printk_skb: 569395 callbacks suppressed
```

**Comment by mgajda** [comment] 2023-01-17 18:19
I found the workaround of `apt-get purge rsyslog` (which is automatically installed).

**Comment by merlijn-sebrechts** [comment] 2023-12-02 20:29
This also seems to be a duplicate of #23 

Let's continue the discussion there.

**Closed by merlijn-sebrechts** 2023-12-02 20:29 UTC
