### ISSUE TITLE
Flooding kernel log with warnings

### ISSUE THREAD

**Issue by michaelaye** [snapcrafters/discord#88] opened 2020-09-14 17:43 UTC
On 
* Kubuntu 20.04
* running NVIDIA driver for GeForce GTX 1660 SUPER
* (however, same errors using the OpenSource drivers)

whenever Discord is running, I get these warnings in the kernel log **with a 1 Hz frequency**!

```
Sep 14 11:38:02 triton kernel: [231369.918236] WARNING: CPU: 8 PID: 133543 at drivers/media/v4l2-core/v4l2-ioctl.c:1064 v4l_querycap+0x8b/0xa0 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918236] Modules linked in: authenc echainiv esp4 xfrm_user xfrm_algo twofish_generic twofish_avx_x86_64 twofish_x86_64_3way twofish_x86_64 twofish_common serpent_avx2 serpent_avx_x86_64 serpent_sse2_x86_64 serpent_generic blowfish_generic blowfish_x86_64 blowfish_common cast5_avx_x86_64 cast5_generic cast_common des_generic libdes camellia_generic camellia_aesni_avx2 camellia_aesni_avx_x86_64 camellia_x86_64 xcbc md4 ccm rfcomm ip6table_filter ip6_tables iptable_filter bpfilter cmac algif_hash algif_skcipher af_alg bnep binfmt_misc snd_hda_codec_hdmi iwlmvm mac80211 nls_iso8859_1 snd_hda_codec_realtek edac_mce_amd snd_hda_codec_generic btusb libarc4 btrtl ledtrig_audio btbcm btintel iwlwifi bluetooth ucsi_ccg eeepc_wmi snd_hda_intel typec_ucsi asus_wmi snd_intel_dspcfg ecdh_generic sparse_keymap ecc snd_hda_codec video joydev k10temp cfg80211 wmi_bmof typec ccp input_leds snd_hda_core kvm snd_hwdep mac_hid nvidia_uvm(OE) sch_fq_codel v4l2loopback(OE) snd_aloop snd_pcm snd_seq_midi
Sep 14 11:38:02 triton kernel: [231369.918253]  snd_seq_midi_event snd_rawmidi snd_seq snd_seq_device snd_timer snd soundcore v4l2loopback_dc(OE) videodev mc parport_pc ppdev lp parport ip_tables x_tables autofs4 hid_logitech_hidpp hid_logitech_dj hid_generic usbhid hid nvidia_drm(POE) nvidia_modeset(POE) nvidia(POE) crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel crypto_simd drm_kms_helper syscopyarea sysfillrect sysimgblt cryptd glue_helper fb_sys_fops drm i2c_piix4 ipmi_devintf nvme ahci ipmi_msghandler r8169 i2c_nvidia_gpu libahci realtek nvme_core wmi
Sep 14 11:38:02 triton kernel: [231369.918269] CPU: 8 PID: 133543 Comm: Discord Tainted: P        W  OE     5.4.0-47-generic #51-Ubuntu
Sep 14 11:38:02 triton kernel: [231369.918269] Hardware name: System manufacturer System Product Name/TUF GAMING X570-PLUS (WI-FI), BIOS 1405 11/19/2019
Sep 14 11:38:02 triton kernel: [231369.918272] RIP: 0010:v4l_querycap+0x8b/0xa0 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918273] Code: 54 81 ca 00 00 00 80 48 b9 00 00 20 00 00 00 20 00 48 0b 4b 54 21 d6 39 f2 75 13 48 89 4b 54 5b 41 5c 41 5d 41 5e 41 5f 5d c3 <0f> 0b eb d0 0f 0b 48 89 4b 54 5b 41 5c 41 5d 41 5e 41 5f 5d c3 0f
Sep 14 11:38:02 triton kernel: [231369.918274] RSP: 0018:ffffa3910a2a7c70 EFLAGS: 00010297
Sep 14 11:38:02 triton kernel: [231369.918275] RAX: 0000000000000000 RBX: ffffa3910a2a7d88 RCX: 0000000000000001
Sep 14 11:38:02 triton kernel: [231369.918275] RDX: 0000000085008003 RSI: 0000000000000000 RDI: 0000000000000000
Sep 14 11:38:02 triton kernel: [231369.918275] RBP: ffffa3910a2a7c98 R08: 0000000000000000 R09: 0000000000ffff0a
Sep 14 11:38:02 triton kernel: [231369.918276] R10: 0000000000000000 R11: 0000000000000000 R12: ffff8a2f6443d000
Sep 14 11:38:02 triton kernel: [231369.918276] R13: ffff8a2d21918000 R14: ffff8a2cf59256c0 R15: ffffffffc1b65380
Sep 14 11:38:02 triton kernel: [231369.918277] FS:  00007fc637105700(0000) GS:ffff8a2f7ea00000(0000) knlGS:0000000000000000
Sep 14 11:38:02 triton kernel: [231369.918277] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep 14 11:38:02 triton kernel: [231369.918278] CR2: 0000123e9ed4c000 CR3: 0000000365bae000 CR4: 0000000000340ee0
Sep 14 11:38:02 triton kernel: [231369.918278] Call Trace:
Sep 14 11:38:02 triton kernel: [231369.918283]  __video_do_ioctl+0x1a7/0x410 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918286]  video_usercopy+0x2b5/0x670 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918289]  ? v4l_s_fmt+0x670/0x670 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918292]  video_ioctl2+0x15/0x20 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918294]  v4l2_ioctl+0x4c/0x60 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918296]  do_vfs_ioctl+0x407/0x670
Sep 14 11:38:02 triton kernel: [231369.918299]  ? __secure_computing+0x42/0xe0
Sep 14 11:38:02 triton kernel: [231369.918300]  ksys_ioctl+0x67/0x90
Sep 14 11:38:02 triton kernel: [231369.918301]  __x64_sys_ioctl+0x1a/0x20
Sep 14 11:38:02 triton kernel: [231369.918302]  do_syscall_64+0x57/0x190
Sep 14 11:38:02 triton kernel: [231369.918305]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Sep 14 11:38:02 triton kernel: [231369.918306] RIP: 0033:0x7fc64a5176d7
Sep 14 11:38:02 triton kernel: [231369.918307] Code: b3 66 90 48 8b 05 b1 47 2d 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 2e 0f 1f 84 00 00 00 00 00 b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 81 47 2d 00 f7 d8 64 89 01 48
Sep 14 11:38:02 triton kernel: [231369.918307] RSP: 002b:00007fc6371047c8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
Sep 14 11:38:02 triton kernel: [231369.918308] RAX: ffffffffffffffda RBX: 0000000000000001 RCX: 00007fc64a5176d7
Sep 14 11:38:02 triton kernel: [231369.918308] RDX: 00007fc637104838 RSI: 0000000080685600 RDI: 000000000000004a
Sep 14 11:38:02 triton kernel: [231369.918308] RBP: 00007fc6371048f0 R08: 0000000000000000 R09: 0000000000000000
Sep 14 11:38:02 triton kernel: [231369.918309] R10: 0000000000000000 R11: 0000000000000246 R12: 00007fc6371048a0
Sep 14 11:38:02 triton kernel: [231369.918309] R13: 0000000000000001 R14: 000000000000004a R15: 0000000000000001
Sep 14 11:38:02 triton kernel: [231369.918310] ---[ end trace 1ba9bd833832855e ]---
Sep 14 11:38:02 triton kernel: [231369.918318] ------------[ cut here ]------------
Sep 14 11:38:02 triton kernel: [231369.918321] WARNING: CPU: 8 PID: 133543 at drivers/media/v4l2-core/v4l2-ioctl.c:1069 v4l_querycap+0x8f/0xa0 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918321] Modules linked in: authenc echainiv esp4 xfrm_user xfrm_algo twofish_generic twofish_avx_x86_64 twofish_x86_64_3way twofish_x86_64 twofish_common serpent_avx2 serpent_avx_x86_64 serpent_sse2_x86_64 serpent_generic blowfish_generic blowfish_x86_64 blowfish_common cast5_avx_x86_64 cast5_generic cast_common des_generic libdes camellia_generic camellia_aesni_avx2 camellia_aesni_avx_x86_64 camellia_x86_64 xcbc md4 ccm rfcomm ip6table_filter ip6_tables iptable_filter bpfilter cmac algif_hash algif_skcipher af_alg bnep binfmt_misc snd_hda_codec_hdmi iwlmvm mac80211 nls_iso8859_1 snd_hda_codec_realtek edac_mce_amd snd_hda_codec_generic btusb libarc4 btrtl ledtrig_audio btbcm btintel iwlwifi bluetooth ucsi_ccg eeepc_wmi snd_hda_intel typec_ucsi asus_wmi snd_intel_dspcfg ecdh_generic sparse_keymap ecc snd_hda_codec video joydev k10temp cfg80211 wmi_bmof typec ccp input_leds snd_hda_core kvm snd_hwdep mac_hid nvidia_uvm(OE) sch_fq_codel v4l2loopback(OE) snd_aloop snd_pcm snd_seq_midi
Sep 14 11:38:02 triton kernel: [231369.918330]  snd_seq_midi_event snd_rawmidi snd_seq snd_seq_device snd_timer snd soundcore v4l2loopback_dc(OE) videodev mc parport_pc ppdev lp parport ip_tables x_tables autofs4 hid_logitech_hidpp hid_logitech_dj hid_generic usbhid hid nvidia_drm(POE) nvidia_modeset(POE) nvidia(POE) crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel crypto_simd drm_kms_helper syscopyarea sysfillrect sysimgblt cryptd glue_helper fb_sys_fops drm i2c_piix4 ipmi_devintf nvme ahci ipmi_msghandler r8169 i2c_nvidia_gpu libahci realtek nvme_core wmi
Sep 14 11:38:02 triton kernel: [231369.918337] CPU: 8 PID: 133543 Comm: Discord Tainted: P        W  OE     5.4.0-47-generic #51-Ubuntu
Sep 14 11:38:02 triton kernel: [231369.918337] Hardware name: System manufacturer System Product Name/TUF GAMING X570-PLUS (WI-FI), BIOS 1405 11/19/2019
Sep 14 11:38:02 triton kernel: [231369.918339] RIP: 0010:v4l_querycap+0x8f/0xa0 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918340] Code: 00 00 80 48 b9 00 00 20 00 00 00 20 00 48 0b 4b 54 21 d6 39 f2 75 13 48 89 4b 54 5b 41 5c 41 5d 41 5e 41 5f 5d c3 0f 0b eb d0 <0f> 0b 48 89 4b 54 5b 41 5c 41 5d 41 5e 41 5f 5d c3 0f 1f 44 00 00
Sep 14 11:38:02 triton kernel: [231369.918340] RSP: 0018:ffffa3910a2a7c70 EFLAGS: 00010202
Sep 14 11:38:02 triton kernel: [231369.918341] RAX: 0000000000000000 RBX: ffffa3910a2a7d88 RCX: 8520800285208002
Sep 14 11:38:02 triton kernel: [231369.918341] RDX: 0000000085008003 RSI: 0000000085008002 RDI: 0000000000000000
Sep 14 11:38:02 triton kernel: [231369.918342] RBP: ffffa3910a2a7c98 R08: 0000000000000000 R09: 0000000000ffff0a
Sep 14 11:38:02 triton kernel: [231369.918342] R10: 0000000000000000 R11: 0000000000000000 R12: ffff8a2f6443d000
Sep 14 11:38:02 triton kernel: [231369.918342] R13: ffff8a2d21918000 R14: ffff8a2cf59256c0 R15: ffffffffc1b65380
Sep 14 11:38:02 triton kernel: [231369.918343] FS:  00007fc637105700(0000) GS:ffff8a2f7ea00000(0000) knlGS:0000000000000000
Sep 14 11:38:02 triton kernel: [231369.918343] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep 14 11:38:02 triton kernel: [231369.918344] CR2: 0000123e9ed4c000 CR3: 0000000365bae000 CR4: 0000000000340ee0
Sep 14 11:38:02 triton kernel: [231369.918344] Call Trace:
Sep 14 11:38:02 triton kernel: [231369.918346]  __video_do_ioctl+0x1a7/0x410 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918349]  video_usercopy+0x2b5/0x670 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918351]  ? v4l_s_fmt+0x670/0x670 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918354]  video_ioctl2+0x15/0x20 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918357]  v4l2_ioctl+0x4c/0x60 [videodev]
Sep 14 11:38:02 triton kernel: [231369.918357]  do_vfs_ioctl+0x407/0x670
Sep 14 11:38:02 triton kernel: [231369.918358]  ? __secure_computing+0x42/0xe0
Sep 14 11:38:02 triton kernel: [231369.918359]  ksys_ioctl+0x67/0x90
Sep 14 11:38:02 triton kernel: [231369.918360]  __x64_sys_ioctl+0x1a/0x20
Sep 14 11:38:02 triton kernel: [231369.918360]  do_syscall_64+0x57/0x190
Sep 14 11:38:02 triton kernel: [231369.918361]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Sep 14 11:38:02 triton kernel: [231369.918362] RIP: 0033:0x7fc64a5176d7
Sep 14 11:38:02 triton kernel: [231369.918362] Code: b3 66 90 48 8b 05 b1 47 2d 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 2e 0f 1f 84 00 00 00 00 00 b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 81 47 2d 00 f7 d8 64 89 01 48
Sep 14 11:38:02 triton kernel: [231369.918363] RSP: 002b:00007fc6371047c8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
Sep 14 11:38:02 triton kernel: [231369.918363] RAX: ffffffffffffffda RBX: 0000000000000001 RCX: 00007fc64a5176d7
Sep 14 11:38:02 triton kernel: [231369.918364] RDX: 00007fc637104838 RSI: 0000000080685600 RDI: 000000000000004a
Sep 14 11:38:02 triton kernel: [231369.918364] RBP: 00007fc6371048f0 R08: 0000000000000000 R09: 0000000000000000
Sep 14 11:38:02 triton kernel: [231369.918364] R10: 0000000000000000 R11: 0000000000000246 R12: 00007fc6371048a0
Sep 14 11:38:02 triton kernel: [231369.918365] R13: 0000000000000001 R14: 000000000000004a R15: 0000000000000001
Sep 14 11:38:02 triton kernel: [231369.918365] ---[ end trace 1ba9bd833832855f ]---
Sep 14 11:38:03 triton kernel: [231370.920746] ------------[ cut here ]------------
```

no change of this since 0.0.10 (now on 0.0.12).

Interestingly, I get the same warnings when using the in-browser app, but with a lower frequency of 1 per 5 seconds.

**Comment by brlin-tw** [comment] 2022-08-13 11:58
> Sep 14 11:38:02 triton kernel: [231369.918236] WARNING: CPU: 8 PID: 133543 at drivers/media/v4l2-core/v4l2-ioctl.c:1064 v4l_querycap+0x8b/0xa0 [videodev]

The v4l2 subsystem warning message indicates there seems to be a bug in your webcam driver, disable the driver may be an acceptable workaround if you do not require it.

**Comment by brlin-tw** [comment] 2022-08-13 12:00
> I get the same warnings when using the in-browser app, but with a lower frequency of 1 per 5 seconds.

As the problem is not snap-specific, closing.  Please reply if you're sure there is something the snap packaging can help, thank you.

**Closed by brlin-tw** 2022-08-13 12:00 UTC
