### ISSUE TITLE
Journal still flooded with AppArmor denials

### ISSUE THREAD

**Issue by TBurchfield** [snapcrafters/discord#96] opened 2021-01-10 12:36 UTC
My journal is still getting flooded with denials of this form:
`Jan 10 07:28:32 computername audit[19283]: AVC apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=19283 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"`
Although `snap info discord` reads:
```
  Snaps are confined, as such Discord may be unable to perform some of the tasks it typically does
  when unconfined. This may result in the system log getting spammed with apparmor errors. Granting
  access to the system-observe interface when in the snap will enable the features, and thus reduce
  the logging.
  
      snap connect discord:system-observe
```
I'm not sure that I want to grant this permission, and would like my logs to not be spammed by these requests anyway.
Based on what I know about AppArmor, giving an explicit denial in the profile for discord should make the logs be quiet.  However, in `/var/lib/snapd/apparmor/profiles/snap.discord.discord` there already exist the lines
```
deny ptrace (trace),
deny capability sys_ptrace,
```
Any idea why the denials are still coming through on the logs?

**Comment by Fuseteam** [comment] 2021-01-10 14:27
this is duplicate issue fwiw, 

the `system-observe` plug doesn't allow it much else than to see what is running on your system fwiw.
discord typically wants to know what is running for its status feature. the thing where it says "fuseteam is playing final fantasy". 

if you want to complete disable that feature, so apparmor doesn't complain, you would need to file a feature request to upstream discord. there's nothing that can be done in this repo to "fix" this. fwiw the discord devs are known to listen to their users, provided enough users vote for the idea

**Comment by Ads20000** [comment] 2021-01-10 21:57
Duplicate of #23

**Comment by Ben64** [comment] 2021-01-11 22:53
#23 was closed unceremoniously and inaccurately. Connecting `system-observe` does remove some of the errors in the logs, but as my last post on #23 showed, it also wants mknod, unlink, open. I've gone through and connected everything I could find to discord, but it still wants more and keeps insisting on flooding my logs. It's ridiculous. I'd like to not give discord every permission there is, but it still doesn't solve the problem of the infinite log spam.

**Comment by Fuseteam** [comment] 2021-01-12 00:47
@Ben64 the original issue of there was solved by connecting system-observe, the thread there was quickly evolving out of scope. I'm going to assume this issue is left open for a reason.
I am currently not able to reproduce the logs you have posted there, how did you got those logs. i suspect it may not be related to discord, but I can ofcourse be wrong.

**Comment by Ben64** [comment] 2021-01-12 06:04
Well the log does mention discord so it seems pretty apparent. It's just incredibly frustrating having my logs full of discord spam

```[810314.339879] audit: type=1400 audit(1610431341.164:157554): apparmor="DENIED" operation="mknod" profile="snap.discord.discord" name="/home/ben64/snap/discord/119/.config/discord/Cache/index-dir/temp-index" pid=5683 comm="ThreadPoolForeg" requested_mask="c" denied_mask="c" fsuid=500 ouid=500```

**Comment by Fuseteam** [comment] 2021-01-12 12:46
@Ben64 i understand, really, but i've seen these logs mention things that weren't on my system (anymore) and didn't make much sense otherwise. fwiw i have discord snap  installed and have connected `system-observe` (and nothing else extra) but afaik i don't have these logs
if you're grepping for it maybe `grep -5` might give a bit more context

**Comment by Ben64** [comment] 2021-01-13 07:20
There is no context, just full log full of discord. I have no idea why it wants access to everything. 

```[15151.539969] audit: type=1400 audit(1610512016.774:69): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/run/mount/utab" pid=2981316 comm="Discord" requested_mask="r" denied_mask="r" fsuid=500 ouid=0
[15151.792949] audit: type=1400 audit(1610512017.026:70): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/run/mount/utab" pid=2981316 comm="Discord" requested_mask="r" denied_mask="r" fsuid=500 ouid=0
[15151.832045] audit: type=1400 audit(1610512017.066:71): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/run/mount/utab" pid=2981316 comm="Discord" requested_mask="r" denied_mask="r" fsuid=500 ouid=0
[15151.904170] audit: type=1400 audit(1610512017.138:72): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/run/mount/utab" pid=2981316 comm="Discord" requested_mask="r" denied_mask="r" fsuid=500 ouid=0
[15158.211900] audit: type=1400 audit(1610512023.446:73): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/run/mount/utab" pid=2981316 comm="Discord" requested_mask="r" denied_mask="r" fsuid=500 ouid=0```

**Comment by Fuseteam** [comment] 2021-01-13 11:44
@Ben64 can you at least share the command your running to get those logs? i can then look if i can find it too.

**Comment by Ben64** [comment] 2021-01-13 18:36
@Fuseteam It was just a simple dmesg that would show it, I've since prevented the spam from reaching my logs and dmesg with a kernel parameter and rsyslogd config. I wouldn't consider that a fix, but it does make my logs usable now.

**Comment by Fuseteam** [comment] 2021-01-14 15:34
guess that's a work around for now, if you want you can share that, meanwhile i can check if i can check if i see the same logs

**Comment by Ben64** [comment] 2021-01-14 23:14
Before doing the workaround, the majority of lines in syslog were just discord spam. And that was after connecting it to system-observe. For example, `/var/log/syslog.3.gz` is 7869 lines long, and 5841 of them mention discord. Of those 5841, 2841 were for `mknod`, 1587 were for `open`, and 1377 were for `unlink`.

**Comment by Fuseteam** [comment] 2021-01-15 04:13
um @Ben64 iiuc `/var/log/syslog.3.gz` is an older archived log, the only relevant one should be `/var/log/syslog`

**Comment by Ben64** [comment] 2021-01-15 10:45
@Fuseteam "older" being 3 days ago, sure I guess. But as I mentioned before, I now have nothing in my logs because I've implemented a workaround. Also as I mentioned before, I've had system-observe connected, along with others and still got the errors I listed, mknod, open, and unlink. system-observe stops ptrace from hitting the logs.

**Comment by Fuseteam** [comment] 2021-01-15 13:59
alright well all i can say @Ben64 is that i am unable to reproduce your logs with system-observe connected on ubuntu 18.04. I have not implemented any other kind of workaround. the only difference that could make a difference that i can think of is that i connected it quite a while ago. 
the logs i do have only appear on application launch and is all explained in the other issue

**Comment by DScottMiller** [comment] 2021-09-26 10:07
I noticed the unlink, open, etc. deny messages occurring recently, and was puzzled to see that they were for paths within the /home/<user>/snap/discord/ directories tree, where one would expect discord to have full permissions.
Checking snap, all snaps were up to date. I restarted discord itself, and it installed updates at launch. After that, the messages stopped appearing.
I'm pretty clueless about how all this works, but maybe it was some sort of version mismatch related to the number that follows /home/<user>/snap/discord/, which was "128" but is now "130." Perhaps the snap service updated the snap to a newer version with a newer apparmor profile that only works for "130" while discord, still running, continued to try to work in the "128" directory tree...or something of that nature.

**Comment by Fuseteam** [comment] 2021-09-27 14:34
and this is the issue with duplicate issues the current status of this is actually addressed in https://github.com/snapcrafters/discord/issues/23#issuecomment-832240529

**Comment by DScottMiller** [comment] 2021-09-27 15:40
Unfortunately, issue #96 is what will turn up on a search when looking for the less common discord apparmor denials like "unlink," while #23's discussion has been about discord's standard behavior with ptrace and the general topic of apparmor logging behavior.

There's a @Fuseteam post in #23 that contains the sentence "My biggest gripe is that when discord decides to bump their version there's a window where discord is simply unusable due to the messy way discord updates their app. " which may be relatable to the content of #96.

**Comment by Fuseteam** [comment] 2021-09-27 15:49
yes that's not only unrelated but also fixed by now, i no longer have that issue; i still stand by my statement that we should solve this issue in a way that will encourage discord themselves to adopt snap packaging as their official packaging. mainly because they would likely appreciate the ability to push updates

**Comment by merlijn-sebrechts** [comment] 2023-12-02 20:27
Closing this as it's a duplicate of #23 

Let's continue the discussion in that issue.

**Closed by merlijn-sebrechts** 2023-12-02 20:27 UTC
