### ISSUE TITLE
Discord Snap is out of date

### ISSUE THREAD

**Issue by benesjan** [snapcrafters/discord#108] opened 2021-05-25 15:52 UTC
![image](https://user-images.githubusercontent.com/13470840/119528981-f7c13f80-bd81-11eb-9582-bfca4c7f2552.png)

**Comment by fwcd** [comment] 2021-05-25 16:25
See #105

**Comment by KorbsStudio** [comment] 2021-05-26 01:21
#105 has been solved, please close this issue.

**Comment by RickAndTired** [comment] 2021-05-26 06:34
> #105 has been solved, please close this issue.

The issue isn't really solved, I'd say that's more of a workaround.
Many users just click the `Install` button for Discord through Ubuntu Software and for the past 24+ hours it hasn't been working.

**Comment by RickAndTired** [comment] 2021-05-26 16:30
I don't think gating the current stable release in a beta channel is a good choice either when the outdated version won't run.

Here are some links of people having trouble with this issue.
https://www.reddit.com/r/Ubuntu/comments/nkxyol/discord_0015_patch/
https://www.reddit.com/r/Ubuntu/comments/nlja1o/cant_see_discord_in_list_of_installed_apps/
https://www.reddit.com/r/Ubuntu/comments/nli73s/new_to_ubuntuhow_to_update_discord_to_version_0015/

**Comment by Hans03430** [comment] 2021-05-26 20:06
They need to push the update to the stable branch :(

**Comment by TopMax** [comment] 2021-05-26 21:03
What is wrong with the update? With the last updates, stable was also updated directly and not beta first.

**Comment by KorbsStudio** [comment] 2021-05-26 21:31
This is a duplicated issue, please view #105.

**Closed** 2021-05-27 07:59 UTC

**Comment by Fuseteam** [comment] 2021-05-27 15:27
i guess the pr explains that @TopMax
