### ISSUE TITLE
Discord policy ptrace problem

### ISSUE THREAD

**Issue by setharnold** [snapcrafters/discord#76] opened 2020-04-08 22:30 UTC
Hello, a user's bug report contains a huge amount of dmesg spam from discord:

https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1871615

https://launchpadlibrarian.net/473598992/Dmesg.txt

This is probably not fun.

Thanks

**Comment by Fuseteam** [comment] 2020-04-09 10:37
Isn't this related to issue #23

**Comment by Ads20000** [comment] 2020-04-09 16:59
Yes pretty sure this is a duplicate of #23, @setharnold see https://github.com/snapcrafters/discord/issues/23#issuecomment-611060991 and/or speak with @jdstrand

**Comment by setharnold** [comment] 2020-04-09 21:27
Ouch, that has been open for almost two years! This poor user got 33 megabytes of kernel logs in two days due to this. If this user has been using this snap for two years, that's almost eight gigabytes of writes due to this one application alone.

We have to be able to do better for our users.

Thanks

**Comment by Fuseteam** [comment] 2020-04-14 15:19
@setharnold feel free to close this one and comment/watch that one btw
also perhaps a feature request to discord could be helpful?

**Comment by Fuseteam** [comment] 2020-08-10 18:13
tbh rich presence is feature of discord
snap connect discord:system-observe seems to silence dmesg

**Closed** 2021-01-11 11:51 UTC
