### ISSUE TITLE
cannot use flags (languages) in channel / categories

### ISSUE THREAD

**Issue by TUXBLN** [snapcrafters/discord#92] opened 2020-10-22 19:53 UTC
when i try to add the icons "🇩🇪" / "🇬🇧" to a channel its like here,
just showing the text DE oder GB in the windows client (!)
Works in mobile though
would be cool to have them implemented so one can see language of channels at a glance

**Comment by Fuseteam** [comment] 2020-10-22 19:59
this is the repo for the linux client. that is likely a font issue

**Comment by TUXBLN** [comment] 2020-10-22 20:01
oh sorry :( wrong repository then :( wher can i post sth for windows

**Comment by Fuseteam** [comment] 2020-10-22 20:16
the windows version has no repository, discord is not open source sadly, perhaps you can do a feature request on discord's user voice.

feel free to close the issue btw. we can still comment even if the issue is closed

**Closed** 2020-11-03 14:47 UTC
