### ISSUE TITLE
Latests versions (52 & 53) 0.0.4 think they are 0.0.1

### ISSUE THREAD

**Issue by mkg20001** [snapcrafters/discord#21] opened 2018-04-01 16:09 UTC
```sh
$ snap info discord
name:      discord
summary:   All-in-one voice and text chat for gamers
publisher: snapcrafters
contact:   https://github.com/snapcrafters/discord/issues
license:   Proprietary
description: |
  All-in-one voice and text chat for gamers that's free, secure, and
  works on both your desktop and phone.
snap-id:     qHVefGEBezeuCeSfTND40uoUD6GRw8BO
channels:               
  stable:    0.0.4 (52) 131MB -
  candidate: 0.0.4 (52) 131MB -
  beta:      0.0.4 (52) 131MB -
  edge:      0.0.4 (53) 127MB -
$ snap install discord --edge
discord (edge) 0.0.4 from 'snapcrafters' installed
$ discord
Discord 0.0.1
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/maciej/.config/discord/0.0.1/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Updates] You are out of date!
[Modules] Host update is available. Manual update required!
```

**Comment by popey** [comment] 2018-04-01 23:42
I can't reproduce this.

```
alan@KinkPad-K450:~$ snap refresh discord --edge
discord (edge) 0.0.4 from 'snapcrafters' refreshed
alan@KinkPad-K450:~$ which discord
/snap/bin/discord
alan@KinkPad-K450:~$ discord
Discord 0.0.4
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/alan/snap/discord/53/.config/discord/0.0.4/modules
[Modules] Module installed file path: /home/alan/snap/discord/53/.config/discord/0.0.4/modules/installed.json
[Modules] Module download path: /home/alan/snap/discord/53/.config/discord/0.0.4/modules/pending
```

I think when you run "discord" you're actually running the deb, not the snap. Notice that the install path is in your home directory. The discord snap is confined, and as such cannot see that directory. So I'm closing this bug as I believe it's a local issue. Thanks for reporting though, it's much appreciated!

**Closed by popey** 2018-04-01 23:42 UTC
